"""
Default constants and hyperparameters for ContLearn.
These can be overridden via JSON config files.
"""

# Random Seeds
DEFAULT_SEED = 5678
DEFAULT_GRAPH_SEED = 10

# Model Architecture Defaults
DEFAULT_CHANNEL_OUT_CNN = 3
DEFAULT_CHANNEL_OUT_CNN3D = 32
DEFAULT_CHANNEL_IN_MNIST = 1
DEFAULT_CHANNEL_IN_CIFAR = 3
DEFAULT_INPUT_SIZE_MNIST = 28
DEFAULT_INPUT_SIZE_CIFAR = 32

# Export DEFAULT_CHANNEL_IN_CIFAR at module level (needed for imports)
__all__ = [
    'DEFAULT_CHANNEL_IN_CIFAR',
    'DEFAULT_CHANNEL_IN_MNIST',
]

# Training Defaults
DEFAULT_BATCH_SIZE_GRAPH = 20
DEFAULT_BATCH_SIZE_VECTOR = 64
DEFAULT_BATCH_SIZE_CLASS = 128
DEFAULT_REPLAY_BUFFER_GRAPH = 200000
DEFAULT_REPLAY_BUFFER_VECTOR = 20000
DEFAULT_TRAIN_TEST_SPLIT = 0.8

# Data Augmentation Defaults
DEFAULT_ROTATION_RANGE = 180
DEFAULT_SCALING_RANGE = (1, 2)
DEFAULT_PERMUTATION_SEED_MULTIPLIER = 1000
DEFAULT_NUM_OMNI_CLASSES = 10
DEFAULT_NUM_OMNI_SELECT = 3

# AWB (Adaptive Weight Basis) Architecture Defaults
DEFAULT_AWB_FILTER_INCREMENT = 2
DEFAULT_AWB_CNN_ARCH = [1875, 700, 100, 10]  # For MNIST/Omniglot CNN
DEFAULT_AWB_CNN3D_HIDDEN = [512, 256]  # For CIFAR CNN3D
DEFAULT_AWB_FNN_ARCH = [100, 140, 140]  # For GCN FNN part
DEFAULT_AWB_GCN_ARCH = [100]  # For GCN part

# Convolution Defaults
DEFAULT_PADDING = 0
DEFAULT_STRIDE = 1
DEFAULT_POOL_SIZE = 2
DEFAULT_POOL_STRIDE = 2

# Architecture Search Defaults
DEFAULT_ARCH_SEARCH_ENABLED = False  # Whether to enable architecture search
DEFAULT_ARCH_SEARCH_START_TASK = 999  # Task number to start arch search (999 = never)
DEFAULT_ARCH_SEARCH_EPOCHS = 100
DEFAULT_ARCH_SEARCH_THRESHOLD = 0.9
DEFAULT_ARCH_SEARCH_MAX_ITER = 10
DEFAULT_ARCH_SEARCH_STEP_SIZE_MLP = 10
DEFAULT_ARCH_SEARCH_STEP_SIZE_GCN = 10
DEFAULT_ARCH_SEARCH_RANGE = 5
DEFAULT_ARCH_SEARCH_FILTER_RANGE = (2, 5)
DEFAULT_ARCH_SEARCH_AVERAGING_WINDOW = 15
DEFAULT_ARCH_SEARCH_MLP_INCREMENT = 15
DEFAULT_ARCH_SEARCH_LARGE_INCREMENT = 250

# Default Architectures by Problem Type
DEFAULT_MLP_REGRESSION_ARCH = None  # Will be inferred from input/output
DEFAULT_CNN_MNIST_ARCH = [1875, 512, 64, 10]
DEFAULT_CNN3D_CIFAR_ARCH = [2304, 512, 256, 10]
DEFAULT_GCN_SIZES = [None, 128]  # First element will be set to input size
DEFAULT_GCN_MLP_SIZES = [128, 128, 128, 10]

# Synthetic Graph Dataset Defaults
DEFAULT_SYNTHETIC_NUM_GRAPHS = 1000
DEFAULT_SYNTHETIC_NUM_CHANNELS = 5
DEFAULT_SYNTHETIC_AVG_NUM_NODES = 2
DEFAULT_SYNTHETIC_NUM_CLASSES = 10

# AWB Training Pipeline Defaults (5-Step Algorithm)
DEFAULT_AWB_ENABLED = False  # Master switch for AWB pipeline
DEFAULT_AWB_PRELIMINARY_EPOCHS = 250  # STEP 1: Epochs to train before checking arch change
DEFAULT_AWB_AB_TRAINING_EPOCHS = 2000  # STEP 3b: Epochs to train A/B matrices
DEFAULT_AWB_AB_WARMUP_EPOCHS = 50  # STEP 5: Warmup epochs after V = AWB^T computation
DEFAULT_AWB_CHANGE_THRESHOLD_HIGH = 0.9  # Ratio threshold to trigger arch change
DEFAULT_AWB_CHANGE_THRESHOLD_MIN_DELTA = 0.01  # Minimum loss increase to trigger change
DEFAULT_AWB_AB_THRESHOLD_BASE = 0.6  # Base threshold for AB training convergence
DEFAULT_AWB_AB_MAX_ITERATIONS = 8  # Maximum iterations for AB training loop
DEFAULT_AWB_AVERAGING_WINDOW = 10  # Number of epochs to average for loss computation
